# Generated by Django 4.2 on 2025-01-21 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sachnoi', '0002_authgroup_authgrouppermissions_authors_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextEntry',
        ),
        migrations.AlterModelTable(
            name='authors',
            table='Authors',
        ),
        migrations.AlterModelTable(
            name='bookaudiofiles',
            table='Book_Audio_Files',
        ),
        migrations.AlterModelTable(
            name='bookreviews',
            table='Book_Reviews',
        ),
        migrations.AlterModelTable(
            name='books',
            table='Books',
        ),
        migrations.AlterModelTable(
            name='categories',
            table='Categories',
        ),
        migrations.AlterModelTable(
            name='userbooks',
            table='User_Books',
        ),
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
